[workspace]
resolver = "2"
members = [
    "crates/zelkova-syntax",
    "crates/zelkova-compiler",
    "crates/zelkova-js",
    "crates/zelkova-test-runner",
    "crates/zelkova",
    "tools/spec-doc",
    "tools/spec-site",
]
default-members = [
    "crates/zelkova-syntax",
    "crates/zelkova-compiler",
    "crates/zelkova-js",
    "crates/zelkova-test-runner",
    "crates/zelkova",
]

[workspace.package]
version = "0.3.0"
authors = ["François Monniot <francoismonniot@gmail.com>"]
