[package]
name = "zelkova-compiler"
version.workspace = true
authors.workspace = true
edition = "2018"

[dependencies]
codespan-reporting = "0.13"
log = "0.4"
petgraph = "0.8"
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"
walkdir = "2.5"
zelkova-syntax = { path = "../zelkova-syntax" }

[dev-dependencies]
indoc = "2.0"
spec-doc = { path = "../../tools/spec-doc" }
